name: Deploy Pages

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetchAndUnzip:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch
        run: wget https://github.com/VentralDigital/website/releases/download/prod/export.zip
      - name: Unzip
        run: unzip export.zip
      - name: Make sure _next folder will be deployed too
        run: touch ./export/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./export
