name: Deploy Pages

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetchAndUnzip:
    runs-on: ubuntu-latest

    steps:
      - name: fetch
        run: wget https://github.com/VentralDigital/website/releases/download/prod/export.zip
      - name: unzip
        run: unzip export.zip
